### ISSUE TITLE
does spherical harmonics data supports for gaussian splatting model visualization?

### ISSUE THREAD

**Issue by hardikdava** [playcanvas/model-viewer#286]
Hello, i wanted to know does the app supports spherical harmonics data in rendering? e.g. with spherical harmonics at 3rd degree.

**Comment by slimbuck** [comment]
Hi @hardikdava ,

No, the model viewer doesn't render with spherical harmonics. Is this important for your use case? Can you explain what you need it for?

In general the extra memory and rendering overhead has meant SH isn't a priority for us, but is something we will add, depending on user requirements.

Thanks!

**Comment by hardikdava** [comment]
@slimbuck thanks for quick reply.

I am working on gaussian splatting and I have observed that there is a huge difference in rendering images with and without spherical harmonics. The rendering with spherical harmonics looks much more promising and detailed. 
Here you can check the difference. I think there should be an option to enable it based on user selection. However, I agree that it might be slow. 

![IMG_20240328_182517.jpg](https://github.com/playcanvas/model-viewer/assets/39372750/169414bd-9fd3-45fa-94b4-6de6ae65cff0)

![IMG_20240328_182452.jpg](https://github.com/playcanvas/model-viewer/assets/39372750/0d20d789-7623-4724-99a2-ee2feea5dd84)

**Comment by slimbuck** [comment]
Hi @hardikdava,

Yes I see. Most of the difference in the overall saturation is because we just throwing away some of the SH data and what's left is desaturated compared to the original. It would be nice if we could figure out a better method of going from SH->color, but till then I guess the only option is to add SH rendering support.

It probably won't be added too quickly, but we'll use this ticket to prioritise the work.

Thanks!

**Comment by mvaligursky** [comment]
It seems most of the difference is just due to the difference in contrast, not due to missing SH data. I loading it your first image into photopea.com, applied contrast (using curve black and while point adjustment), and the image looks very similar to the point of not being able to tell the difference.

Depending on what viewer is used, you could check if it has contrast controls or similar, or at least what tone mapping iss used.

![Screenshot 2024-04-03 at 15 48 16](https://github.com/playcanvas/model-viewer/assets/59932779/fee529f7-9993-41c2-b81a-1c2a7b697038)
